setup(name='CCDDroneGUI',
      version='0.2',
      description='Database and web wrapper for CCDDrone',
      url='https://stash.pnnl.gov/projects/CAS/repos/ccddronegui/browse',
      author='Ben Loer and Pitam Mitra',
      author_email='ben.loer@pnnl.gov',
      packages=find_packages(),
      py_modules=['ImageDB','CCDDroneGUI','CCDDExposeDB','CCDDUpdateDB'],
      package_data={},
      data_files=[('web',['templates/*.html','static/*','static/*/*'],)],
      zip_safe=False,
      install_requires=[
          'flask',
          'flask-wtf',
          'flask-bootstrap',
          'pymongo',
          'astropy',
          'gunicorn',
      ],
)
