####### Web Application configuration #########
## Web app logs
LOGFILE = 'logs/CCDDroneGUI.log'
LOGLEVEL = 'WARNING'
## Logs for CCDDrone executables
EXECUTOR_LOGFILE = 'logs/Executor.log'

## Put application in DEBUG mode? Not quite sure what the differences are
DEBUG = False
TESTING = False

## If BASIC_AUTH_FORCE is true, password-protect the site
BASIC_AUTH_USERNAME = 'ccduser'
BASIC_AUTH_PASSWORD = 'ccduser'
#BASIC_AUTH_FORCE = True

## Database configuration
IMAGEDB_URI = "mongodb://localhost/ccddrone"
IMAGEDB_COLLECTION = "ccdimages"

## External links section of navbar. List of (url, label) pairs
#SITE_EXTERNAL_LINKS = []

####### CCDDrone configuration #############
## where are output .fits files stored?
DATAPATH = 'data'
## Where are the CCDDrone code and binaries?
CCDDRONEPATH = 'DummyDrone'
## Name for CCDDrone config file generated by GUI (relative to CCDDRONEPATH)
CCDDCONFIGFILE = 'config/Config_GUI.ini'
## Name for metadata file generated by GUI (relative to CCDDRONEPATH)
CCDDMETADATAFILE = 'config/Metadata_GUI.json'


