#!/bin/bash -e

EXPOSURE="$1"
if [ -z "#EXPOSURE" ] ; then
    echo "Please specifiy an exposure value"
    echo "Usage: $0 [exp time (s) : Default = 5] [Output file name: Default Image.fits]"
    exit 1
fi

OUTFILE="$2"
[ -z "$OUTFILE" ] && OUTFILE="Image.fits"
if [ -f "$OUTFILE" ] ; then
    echo "The specified output file already exist. Please specify a different name for the output."
    exit -1
fi

echo "Turning VDD OFF before exposure."
echo "Starting exposure"
sleep $EXPOSURE
echo "Total pixels to read: XXX"
for i in `seq 100` ; do
    echo -ne "["
    printf '=%.0s' `seq $(( i / 2 ))`
    printf ' %.0s' `seq $(( (101-i)/2 ))`
    echo -ne "] ${i}%  | Est. time remaining $(( 100 - i ))s\r"
    sleep 1
done
echo
./FakeImage.py $OUTFILE
echo "Exposure complete."
